config/routes.rb
Medusa::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get "surfaces/index"
  get "surfaces/show"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: "users"
             }
  resources :tokens, only: :create

  root 'records#index'

  concern :bundleable do
    collection do
      post :bundle_edit
      post :bundle_update
    end
  end

  concern :reportable do
    member do
      get :download_card
      get :download_label
    end
    collection do
      get :download_bundle_card
      get :download_bundle_label
      get :download_bundle_list
    end
  end

  concern :link_by_global_id do
    collection do
      post :link_by_global_id
    end
  end

  concern :inventory do
    member do
      post :inventory
    end
  end

  concern :multiple do
    collection do
      get :multiple_new
      post :multiple_create
    end
  end

  concern :sesar_upload do
    member do
      post :sesar_upload
    end
  end

  resources :records, { id: /((?!\.(html$|json$|xml$|pml$)).)*/ } do
    member do
      get 'record_property' => 'records#property'
      get 'casteml'
      get 'ancestors'
      get 'descendants'
      get 'self_and_descendants'
      get 'pmlame'
      get 'root'
      get 'parent'
      get 'daughters'
      get 'siblings'
      get 'self_and_siblings'
      get 'families'
      put :dispose
      patch :dispose
      put :restore
      patch :restore
      put :lose
      patch :lose
      put :found
      patch :found
      put :publish
      patch :publish
    end
  end

  resources :specimens, concerns: [:bundleable, :reportable, :sesar_upload], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      get :detail_edit
      get :chemistries
      get :place, to: :show_place
      post :place, to: :create_place
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "specimen" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "specimen" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "specimen" }
    resources :daughters, concerns: [:link_by_global_id], only: [:index, :create,:update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "specimen" }
  end

  resources :divide_specimens, only: [:update] do
    member do
      put :loss
    end
  end

  resources :divides, only: [:edit, :update, :destroy] do
    member do
      put :loss
    end
  end

  resources :boxes, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :property
      get :tree_node
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "box" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "box" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "box" }
    resources :specimens, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "box", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "box", association_name: "children" }
  end

  resources :places, concerns: [:bundleable, :reportable] do
    member do
      get :map
      get :property
    end
    collection do
      post :import
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id],only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "place" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "place", association_name: "specimens" }
  end

  resources :analyses, concerns: :bundleable do
    member do
      get :picture
      get :property
      get :casteml
    end
    collection do
      post :import
      get :table
      get :castemls
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "analysis" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "analysis" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "analysis" }
    resources :chemistries, concerns: [:multiple],only: [:index, :create, :update, :destroy], controller: "nested_resources/chemistries"
  end

  resources :bibs, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      put :publish
    end
    collection do
      get :download_to_tex
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "bib" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "bib", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "bib", association_name: "boxes" }
    resources :places, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/places", defaults: { parent_resource: "bib", association_name: "places" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "bib", association_name: "analyses" }
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "bib" }
    resources :tables, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/tables", defaults: { parent_resource: "bib" }
  end

  resources :surfaces, concerns: [:bundleable, :reportable] do
    member do
      get :family
      get :picture
      get :property
      get :map
    end
    resources :images, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_images" do
      member do
        get :family
        post 'move_to_top'
        post 'tiles'
        get :calibrate
      end
    end
    resources :spots, only: [:index, :create, :update, :destroy], controller: "nested_resources/spots"
    resources :layers, only: [:show, :create, :edit, :update, :destroy], controller: "surface_layers" do
      member do
        post 'move_to_top'
      end
    end
  end

  resources :tables, except: [:new] do
    member do
      get :property
      put :publish
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "table", association_name: "specimens" }
  end

  resources :attachment_files, concerns: :bundleable , except: [:new] do
    member do
      get :property
      get :picture
      get :download
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "attachment_file" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore

app/controllers/bibs_controller.rb
class BibsController < ApplicationController
  respond_to :html, :xml, :json
  before_action :find_resource, except: [:index, :create, :bundle_edit, :bundle_update, :download_bundle_card, :download_label, :download_bundle_label, :download_to_tex]
  before_action :find_resources, only: [:bundle_edit, :bundle_update, :download_bundle_card, :download_bundle_label, :download_to_tex]
  load_and_authorize_resource

  def index
    @search = Bib.includes(bib_authors: :author).readables(current_user).order("bib_authors.priority").search(params[:q])
    @search.sorts = "updated_at DESC" if @search.sorts.empty?
    @bibs = @search.result.page(params[:page]).per(params[:per_page])
    respond_with @bibs
  end

  def show
    respond_with @bib
  end

  def edit
    respond_with @bib, layout: !request.xhr?
  end

  def create
    @bib = Bib.new(bib_params)
    @bib.save
    respond_with @bib
  end

  def update
    @bib.update_attributes(bib_params)
    respond_with @bib
  end

  def publish
    #@bib.publish!
    PublishWorker.perform_async(@bib.global_id)
    respond_with @bib
  end
  
  def destroy
    @bib.destroy
    respond_with @bib
  end

  def family
    respond_with @bib, layout: !request.xhr?
  end

  def picture
    respond_with @bib, layout: !request.xhr?
  end
  
  def map
    respond_with @bib, layout: !request.xhr?
  end

  def property
    respond_with @bib, layout: !request.xhr?
  end

  def bundle_edit
    respond_with @bibs
  end

  def bundle_update
    @bibs.each { |bib| bib.update_attributes(bib_params.only_presence) }
    render :bundle_edit
  end

  def download_bundle_card
    method = (params[:a4] == "true") ? :build_a_four : :build_cards
    report = Bib.send(method, @bibs)
    send_data(report.generate, filename: "bibs.pdf", type: "application/pdf")
  end

  def download_label
    bib = Bib.find(params[:id])
    send_data(bib.build_label, filename: "bib_#{bib.id}.label", type: "text/label")
  end

  def download_bundle_label
    label = Bib.build_bundle_label(@bibs)
    send_data(label, filename: "bibs.label", type: "text/label")
  end
  
  def download_to_tex
    tex = Bib.build_bundle_tex(@bibs)
    send_data(tex, filename: "bibs.bib", type: "text")
  end

  private

  def bib_params
    params.require(:bib).permit(
      :entry_type,
      :abbreviation,
      :name,
      :journal,
      :year,
      :volume,
      :number,
      :pages,
      :month,
      :abstract,
      :summary,
      :note,
      :key,
      :link_url,
      :doi,
      :user_id,
      :group_id,
      :published,
      author_ids: [],
      record_property_attributes: [
        :id,
        :global_id,
        :user_id,
        :group_id,
        :owner_readable,
        :owner_writable,
        :group_readable,
        :group_writable,
        :guest_readable,
        :guest_writable,
        :published,
        :lost
      ],
      bib_authors_attributes: [
        :id,
        :priority
      ]
    )
  end

  def find_resource
    @bib = Bib.find(params[:id]).decorate
  end

  def find_resources
    @bibs = Bib.where(id: params[:ids])
  end

end

app/controllers/nested_resources/bibs_controller.rb
class NestedResources::BibsController < ApplicationController

  respond_to :html, :xml, :json
  before_action :find_resource
  load_and_authorize_resource

  def index
    @bibs = @parent.bibs
    respond_with @bibs
  end

  def create
    @bib = Bib.new(bib_params)
    @parent.bibs << @bib if @bib.save
    respond_with @bib, location: adjust_url_by_requesting_tab(request.referer), action: "error"
  end

  def update
    @bib = Bib.find(params[:id])
    @parent.bibs << @bib
    respond_with @bib, location: adjust_url_by_requesting_tab(request.referer)
  end

  def destroy
    @bib = Bib.find(params[:id])
    @parent.bibs.delete(@bib)
    respond_with @bib, location: adjust_url_by_requesting_tab(request.referer)
  end

  def link_by_global_id
    @bib = Bib.joins(:record_property).where(record_properties: {global_id: params[:global_id]}).readonly(false).first
    @parent.bibs << @bib if @bib
    respond_with @bib, location: adjust_url_by_requesting_tab(request.referer), action: "error"
  rescue
    duplicate_global_id
  end

  private

  def bib_params
    params.require(:bib).permit(
      :entry_type,
      :abbreviation,
      :name,
      :journal,
      :year,
      :volume,
      :number,
      :pages,
      :month,
      :note,
      :key,
      :link_url,
      :doi,
      :user_id,
      :group_id,
      author_ids: [],
      record_property_attributes: [
        :global_id,
        :user_id,
        :group_id,
        :owner_readable,
        :owner_writable,
        :group_readable,
        :group_writable,
        :guest_readable,
        :guest_writable,
        :published,
        :published_at
      ]
    )
  end

  def find_resource
    resource_name = params[:parent_resource]
    resource_class = resource_name.camelize.constantize
    @parent = resource_class.find(params["#{resource_name}_id"])
  end

  def duplicate_global_id
    respond_to do |format|
      format.html { render "parts/duplicate_global_id", status: :unprocessable_entity }
      format.all { render nothing: true, status: :unprocessable_entity }
    end
  end

end

app/views/bibs/_bib.modal.erb
<tr>
  <td>
    <%= button_tag class: "btn btn-default btn-xs determine", "data-id" => bib.global_id do %>
    <span class="glyphicon glyphicon-link"></span>
    <% end %>
  </td>
  <td><%= link_to bib.name, bib_path(bib, format: :modal), "data-toggle" => "modal", "data-target" => "#show-modal" %></td>
  <td><%= bib.try!(:doi) %></td>
  <td><%= bib.authors.map {|author| author.name }.join(" & ")%></td>
  <td><%= bib.try!(:year) %></td>
  <td><%= bib.try!(:entry_type) %></td>
  <td><%= bib.group.try!(:name) %></td>
  <td><%= difference_from_now(bib.updated_at) %></td>
</tr>

app/views/bibs/_box.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>box-type</th>
      <th></th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag bundle_edit_boxes_path, id: "box-bundle-form" do %>
      <% @bib.boxes.each do |box| %>
        <tr>
          <td>
            <%= check_box_tag("ids[]", box.id, false, {id: "ids_#{box.id}", class: "select-row"}) if can?(:update, box) %>
          </td>
          <td><%= link_to_if can?(:read, box), list_title(box),box %></td>
          <td><%= box.box_type.try!(:name) %></td>
          <td></td>
          <td><%= box.try!(:global_id) %></td> 
          <td>
            <%= link_to bib_box_path(@bib,box) + tab_param(__FILE__), method: :delete ,title: "unlink box",data: {confirm: t("confirm.unlink")} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_for Box.new, url: bib_boxes_path(@bib) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th><%= f.text_field :name, class: "form-control input-sm" %></th>
        <th><%= f.select :box_type_id, BoxType.pluck(:name, :id), { include_blank: true }, class: "form-control input-sm" %></th>
        <th>
          <%= f.button title:"add box file", class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
      <%= form_tag link_by_global_id_bib_boxes_path(@bib), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, nil, id: "box-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to boxes_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#box-global-id" do %>
	      <span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link box by global id", class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </tfoot>
</table>
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#box-bundle-form').submit();", class: "btn btn-default" %>

app/views/bibs/_place.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>latitude</th>
      <th>longitude</th>
      <th></th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag bundle_edit_places_path, id: "place-bundle-form" do %>
      <% @bib.all_places.each do |place| %>
        <% next unless place %>
        <tr>
          <td>
            <%= check_box_tag("ids[]", place.id, false, {id: "ids_#{place.id}", class: "select-row"}) if can?(:update, place) %>
          </td>
          <td><%= link_to_if can?(:read, place), list_title(place), place %></td>
          <td><%= place.decorate.latitude_to_text %></td>
          <td><%= place.decorate.longitude_to_text %></td>
          <td></td>
          <td><%= place.try!(:global_id) %></td> 
          <td>
            <%= link_to bib_place_path(@bib, place) + tab_param(__FILE__), method: :delete, title: "unlink place", data: {confirm: t("confirm.unlink")} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_for Place.new, url: bib_places_path(@bib) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th><%= f.text_field :name, class: "form-control input-sm" %></th>
        <th><%= f.text_field :latitude, class: "form-control input-sm" %></th>
        <th><%= f.text_field :longitude, class: "form-control input-sm" %></th>
        <th>
          <%= f.button title:"add box file", class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
      <%= form_tag link_by_global_id_bib_places_path(@bib),method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, nil, id: "place-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to places_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#place-global-id" do %>
	      <span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link place by global id",class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </tfoot>
</table>
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#place-bundle-form').submit();", class: "btn btn-default" %>

app/views/bibs/_specimen.html.erb
<div class="row">



<%= form_tag bundle_edit_specimens_path, id: "specimen-bundle-form" do %>
<% specimen_groups = @bib.specimens.group_by{|specimen| specimen.box} %>
<% specimen_groups.each do |box, specimens| %>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
    <% if box %>
        <%= box.decorate.box_path_with_id %>
        <%# links = [content_tag(:div, qrcode(box.global_id, size: "80x80"), class: "col-xs-2 col-sm-2 col-md-2 col-lg-2") ] %>
        <% links = [] %>
        <% box.related_spots.each do |spot| %>
        <% svg_link = link_to(spot_path(spot)) do %>
          <% spot.attachment_file.decorate.picture_with_spots(width:120, height:90, spots:[spot]) %>
        <% end %>
          <% links << content_tag(:div, svg_link, class: "col-xs-2 col-sm-2 col-md-2 col-lg-2") %>
        <% end %>
        <%= content_tag(:div, raw( links.join ), class: "row spot-thumbnails") %>
    <% end %>
    </div>
    <table class="table table-condensed">
      <% specimens.each do |specimen| %>
      <% specimen = specimen.decorate %>
      <tr>
      <td class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
          <%= qrcode specimen.global_id, size: "80x80" %>
          <%= check_box_tag("ids[]", specimen.id, true, {id: "ids_#{specimen.id}", class: "select-row"}) if can?(:update, specimen) %>
          <%= link_to bib_specimen_path(@bib, specimen) + tab_param(__FILE__), method: :delete, title: "unlink specimen", data: {confirm: t("confirm.unlink")} do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
      </td>
      <td class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <%= link_to specimen.attachment_files.first.decorate.picture(width: 160, height: 160, type: :thumb), specimen, class: specimen_ghost(specimen) if specimen.attachment_files.present? %>
      </td>

      <td class="col-xs-7 col-sm-7 col-md-7 col-lg-7">

        <%= specimen.name_with_id(true) %>
        <ul>
          <% unless specimen.igsn.blank? %>
            <li>
              IGSN: <%= link_to specimen.igsn, Settings.sesar_url(igsn: specimen.igsn) %>
          <%= link_to Settings.sesar_url(igsn: specimen.igsn, edit: true), title: "edit on SESAR" do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>

            </li>
          <% end %>
          <% if specimen.place %>
            <% place = specimen.place.decorate %>
            <li>
              place: <%= raw(place.try!(:latitude_to_html)) + ", " + raw(place.try!(:longitude_to_html)) %> <%= link_to "more", place_path(place) %>
            </li>
          <% end %>
          <%= li_if_exist("classification: ", specimen.classification.try!(:full_name)) %>
          <%= li_if_exist("physical-form: ", specimen.physical_form.try!(:name)) %>
          <%= li_if_exist("quantity (#{specimen.quantity_unit}): ", specimen.quantity) %>
          <%= content_tag(:li, "status: #{specimen.status_icon} (#{specimen.status_name})", {}, false) if specimen.status_name.present? %>
          <%= li_if_exist("age (#{specimen.age_unit}): ", specimen.age_in_text) %>
          <%= li_if_exist("tag list: ", specimen.tag_list) %>
          <%= li_if_exist("description: ", specimen.description) %>
          <% specimen.specimen_custom_attributes.each do |specimen_custom_attribute| %>
            <%= li_if_exist("#{specimen_custom_attribute.custom_attribute.name}: ", specimen_custom_attribute.value ) %>
          <% end %> 
          <li>modified at <%= difference_from_now(specimen.updated_at) %></li>
        </ul>      
      </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<% end %>
<% end %>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#specimen-bundle-form').submit();", class: "btn btn-default" %>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
    </div>
    <table class="table table-condensed">
      <tr>
      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <%= form_tag link_by_global_id_bib_specimens_path(@bib),method: :post do %>
          <%= hidden_tabname_tag(__FILE__) %>
            <div class="input-group"> 
            <%= text_field_tag :global_id, nil, id: "specimen-global-id", :placeholder => "input ID", class: "form-control input-sm" %>
            <span class="input-group-addon">
              <%= link_to specimens_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#specimen-global-id" do %>
                <span class="glyphicon glyphicon-search"></span>
              <% end %>
            </span>

            </div>
              <%= button_tag title: "link specimen by global id", class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-save"></span>
              <% end %>
        <% end %>
      </td>
      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

          <%= form_for Specimen.new, url: bib_specimens_path(@bib) do |f|%>
            <%= hidden_tabname_tag(__FILE__) %>
            <%= f.text_field :name, :placeholder => "input name", class: "form-control input-sm" %>
            <%= f.select :physical_form_id, PhysicalForm.pluck(:name, :id), { prompt: "select physical form" }, class: "form-control input-sm" %>
            <%= f.text_field :quantity, :placeholder => "input quantity", class: "form-control input-sm" %>
            <%= f.text_field :quantity_unit, :placeholder => "input quantity unit", class: "form-control input-sm" %>
              <%= f.button title:"add specimen file", class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-save"></span>
              <% end %>
          <% end %>
      </td>
      </tr>
    </table>
  </div>
</div>

</div>

app/views/bibs/family.html.erb
<% cache @bib do %>
<div>
  <% if @bib.attachment_files.present? %>
    <%= link_to(@bib.primary_picture(width: 390), attachment_file_path(@bib.attachment_files.first), class: specimen_ghost(@bib)) %>
  <% end %>
  <ul>
    <% if false && @bib.abstract? %><li>abstract: <%= simple_format(@bib.abstract) %></li><% end %>
    <% if false && @bib.summary? %><li>summary: <%=simple_format(@bib.summary)%></li><% end %>
  </ul>
</div>
<div id="family-tree">
  <%= @bib.family_tree %>
</div>
<% end %>

app/views/bibs/property.html.erb
<%= render partial: "parts/property", locals: { record: @bib } %>

<%= javascript_tag do %>
  $(document).on("succeed.ajaxForm", "#edit_bib_<%= @bib.id %>", function() {
    location.href="<% bib_path(@bib) %>";
  });
<% end %>