config/routes.rb
Medusa::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get "surfaces/index"
  get "surfaces/show"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: "users"
             }
  resources :tokens, only: :create

  root 'records#index'

  concern :bundleable do
    collection do
      post :bundle_edit
      post :bundle_update
    end
  end

  concern :reportable do
    member do
      get :download_card
      get :download_label
    end
    collection do
      get :download_bundle_card
      get :download_bundle_label
      get :download_bundle_list
    end
  end

  concern :link_by_global_id do
    collection do
      post :link_by_global_id
    end
  end

  concern :inventory do
    member do
      post :inventory
    end
  end

  concern :multiple do
    collection do
      get :multiple_new
      post :multiple_create
    end
  end

  concern :sesar_upload do
    member do
      post :sesar_upload
    end
  end

  resources :records, { id: /((?!\.(html$|json$|xml$|pml$)).)*/ } do
    member do
      get 'record_property' => 'records#property'
      get 'casteml'
      get 'ancestors'
      get 'descendants'
      get 'self_and_descendants'
      get 'pmlame'
      get 'root'
      get 'parent'
      get 'daughters'
      get 'siblings'
      get 'self_and_siblings'
      get 'families'
      put :dispose
      patch :dispose
      put :restore
      patch :restore
      put :lose
      patch :lose
      put :found
      patch :found
      put :publish
      patch :publish
    end
  end

  resources :specimens, concerns: [:bundleable, :reportable, :sesar_upload], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      get :detail_edit
      get :chemistries
      get :place, to: :show_place
      post :place, to: :create_place
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "specimen" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "specimen" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "specimen" }
    resources :daughters, concerns: [:link_by_global_id], only: [:index, :create,:update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "specimen" }
  end

  resources :divide_specimens, only: [:update] do
    member do
      put :loss
    end
  end

  resources :divides, only: [:edit, :update, :destroy] do
    member do
      put :loss
    end
  end

  resources :boxes, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :property
      get :tree_node
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "box" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "box" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "box" }
    resources :specimens, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "box", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "box", association_name: "children" }
  end

  resources :places, concerns: [:bundleable, :reportable] do
    member do
      get :map
      get :property
    end
    collection do
      post :import
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id],only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "place" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "place", association_name: "specimens" }
  end

  resources :analyses, concerns: :bundleable do
    member do
      get :picture
      get :property
      get :casteml
    end
    collection do
      post :import
      get :table
      get :castemls
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "analysis" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "analysis" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "analysis" }
    resources :chemistries, concerns: [:multiple],only: [:index, :create, :update, :destroy], controller: "nested_resources/chemistries"
  end

  resources :bibs, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      put :publish
    end
    collection do
      get :download_to_tex
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "bib" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "bib", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "bib", association_name: "boxes" }
    resources :places, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/places", defaults: { parent_resource: "bib", association_name: "places" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "bib", association_name: "analyses" }
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "bib" }
    resources :tables, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/tables", defaults: { parent_resource: "bib" }
  end

  resources :surfaces, concerns: [:bundleable, :reportable] do
    member do
      get :family
      get :picture
      get :property
      get :map
    end
    resources :images, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_images" do
      member do
        get :family
        post 'move_to_top'
        post 'tiles'
        get :calibrate
      end
    end
    resources :spots, only: [:index, :create, :update, :destroy], controller: "nested_resources/spots"
    resources :layers, only: [:show, :create, :edit, :update, :destroy], controller: "surface_layers" do
      member do
        post 'move_to_top'
      end
    end
  end

  resources :tables, except: [:new] do
    member do
      get :property
      put :publish
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "table", association_name: "specimens" }
  end

  resources :attachment_files, concerns: :bundleable , except: [:new] do
    member do
      get :property
      get :picture
      get :download
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "attachment_file" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore

app/controllers/nested_resources/specimens_controller.rb
class NestedResources::SpecimensController < ApplicationController

  respond_to  :html, :xml, :json
  before_action :find_resource
  load_and_authorize_resource

  def index
    @specimens = @parent.send(params[:association_name])
    respond_with @specimens
  end

  def create
    @specimen = Specimen.new(specimen_params)
    ActiveRecord::Base.transaction do
    	 succeed = @parent.send(params[:association_name]) << @specimen if @specimen.save
      raise ActiveRecord::Rollback unless succeed
    end
    respond_with @specimen, location: adjust_url_by_requesting_tab(request.referer), action: "error" 
  end

  def update
    @specimen = Specimen.find(params[:id])
    @parent.send(params[:association_name]) << @specimen
    respond_with @specimen
  end

  def destroy
    @specimen = Specimen.find(params[:id])
    @parent.send(params[:association_name]).delete(@specimen)
    respond_with @specimen, location: adjust_url_by_requesting_tab(request.referer)
  end

  def link_by_global_id
    @specimen = Specimen.joins(:record_property).where(record_properties: {global_id: params[:global_id]}).readonly(false).first
    @parent.send(params[:association_name]) << @specimen if @specimen
    respond_with @specimen, location: adjust_url_by_requesting_tab(request.referer), action: "error"
  rescue
    duplicate_global_id
  end
  
  def inventory
    @specimen = Specimen.find(params[:id])
    @specimen.update_attributes(box_id: params[:box_id])
    @specimen.paths.current.first.update_attribute(:checked_at, Time.now) if @specimen.paths.current.first
    respond_with @specimen
  end

  private

  def specimen_params
    params.require(:specimen).permit(
      :name,
      :physical_form_id,
      :classification_id,
      :quantity,
      :quantity_unit,
      :tag_list,
      :parent_id,
      :box_id,
      :place_id,
      :description,
      :igsn,
      :age_min,
      :age_max,
      :age_unit,
      :size,
      :size_unit,
      :collector,
      :collector_detail,
      :collected_at,
      :collection_dateprecision,
    record_property_attributes: [
        :global_id,
        :user_id,
        :group_id,
        :owner_readable,
        :owner_writable,
        :group_readable,
        :group_writable,
        :guest_readable,
        :guest_writable,
        :published,
        :published_at
      ]
    )
  end

  def find_resource
    resource_name = params[:parent_resource]
    resource_class = resource_name.camelize.constantize
    @parent = resource_class.find(params["#{resource_name}_id"])
  end

  def duplicate_global_id
    respond_to do |format|
      format.html { render "parts/duplicate_global_id", status: :unprocessable_entity }
      format.all { render nothing: true, status: :unprocessable_entity }
    end
  end

end

app/views/specimens/_analysis.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>device</th>
      <th></th>
      <th>size</th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag bundle_edit_analyses_path, id: "analysis-bundle-form" do %>
      <% @specimen.full_analyses.each do |analysis| %>
        <tr>
          <td>
            <%= check_box_tag("ids[]", analysis.id, false, {id: "ids_#{analysis.id}", class: "select-row"}) if can?(:update, analysis) %>
          </td>
          <td><%= link_to_if can?(:read, analysis), list_title(analysis), analysis %></td>
          <td><%= analysis.device.try!(:name) %></td>
          <td></td>
          <td><%= analysis.chemistries.size %></td>
          <td><%= analysis.try!(:global_id) %></td> 
          <td>
            <%= link_to specimen_analysis_path(@specimen, analysis) + tab_param(__FILE__), method: :delete, title: "unlink analysis", data: {confirm: t("confirm.unlink")} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_for Analysis.new, url: specimen_analyses_path(@specimen) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th><%= f.text_field :name, class: "form-control input-sm" %></th>
        <th><%= f.select :device_id, Device.pluck(:name, :id), { include_blank: true }, class: "form-control input-sm" %></th>
        <th>
          <%= f.button title:"add analysis file",class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
        <th></th>
      <% end %>
      <%= form_tag link_by_global_id_specimen_analyses_path(@specimen),method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, nil, id: "analysis-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to analyses_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#analysis-global-id" do %>
	      <span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link analysis by global id", class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </tfoot>
</table>
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#analysis-bundle-form').submit();", class: "btn btn-default" %>

app/views/specimens/_bib.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th colspan= "2">name</th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag bundle_edit_bibs_path, id: "bib-bundle-form" do %>
      <% @specimen.bibs.each do |bib| %>
        <tr>
          <td>
              <%= check_box_tag("ids[]", bib.id, checked: false, id: "ids_#{bib.id}", class: "select-row") if can?(:update, bib) %>
            </td>
          <td colspan="2"><%= link_to_if can?(:read, bib), list_title(bib), bib %></td>
          <td><%= bib.try!(:global_id) %></td>
          <td>
            <%= link_to specimen_bib_path(@specimen,bib) + tab_param(__FILE__), method: :delete ,title: "unlink bib",data: {confirm: t("confirm.unlink")} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
     <%= form_for Bib.new, url: specimen_bibs_path(@specimen) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th><%#= f.text_field :name, class: "form-control input-sm" %></th>
        <th>
          <%#= f.button title:"add bib",class: "btn btn-default" do %>
            <%#<span class="glyphicon glyphicon-save"></span>%>
          <%# end %>
        </th>
      <% end %>
    <%= form_tag link_by_global_id_specimen_bibs_path(@specimen), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, "", id: "bib-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to bibs_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#bib-global-id" do %>
	      <span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link bib by global id",class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
    <tr>
  </tfoot>
</table>
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#bib-bundle-form').submit();", class: "btn btn-default" %>

app/views/specimens/_daughter.html.erb
<div class="display-type">
  <div id="display-type-html">
    <%= form_tag bundle_edit_specimens_path, id: "specimen-bundle-form" do %>
      <div class="row">
        <div  class="col-sm-1">
        </div>      
        <div  class="col-sm-2">
          name
        </div>
        <div class="col-sm-2">
          physical-form
        </div>
        <div class="col-sm-2">
          quantity
        </div>
      </div>
      <div class="daughter">
      <% @specimen.children.each do |specimen| %>
        <div class="row">
          <div  class="col-sm-1">
            <%= check_box_tag("ids[]", specimen.id, false, {id: "ids_#{specimen.id}", class: "select-row"}) if can?(:update, specimen) %>
          </div>
          <div class="col-sm-2">
            <%= specimen.decorate.status_icon %>
            <%= link_to_if can?(:read, specimen), list_title(specimen), specimen, class: specimen_ghost(specimen) %>
          </div>
          <div class="col-sm-2">
            <%= specimen.physical_form.try!(:name) %>
          </div>
          <div class="col-sm-2">
            <%= specimen.try!(:quantity) %>
            <%= specimen.try!(:quantity_unit) %>
          </div>
          <div class="col-sm-4">
          <%= specimen.try!(:global_id) %>
          </div>
          <div class="col-sm-1">            
              <%= link_to specimen_daughter_path(@specimen, specimen) + tab_param(__FILE__), method: :delete, title: "unlink specimen", data: {confirm: t("confirm.unlink")} do %>
                <span class="glyphicon glyphicon-remove"></span>
              <% end %>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
    <div class="row">
      <div class="col-sm-2">
        <% unless @specimen.children.empty? %>
          <%= check_box_tag nil, nil, false, class: "select-row-all" %>
          <%#= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#specimen-bundle-form').submit();", class: "btn btn-default" %>
        <% end %>
      </div>
      <%= form_tag link_by_global_id_specimen_daughters_path(@specimen), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <div class="col-sm-offset-5 col-sm-4">
          <div class="input-group">
            <%= text_field_tag :global_id, nil, id: "daughter-global-id", class: "form-control input-sm" %>
            <span class="input-group-addon">
              <%= link_to specimens_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#daughter-global-id" do %>
                <span class="glyphicon glyphicon-search"></span>
              <% end %>
            </span>
          </div>
        </div>
        <div class="col-sm-1">            
          <%= button_tag title: "link specimen by global id", class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= form_for @divide_specimen, url: divide_specimen_path, remote: true, format: :json, html: { class: "update", role: "form", id: "divide_specimen" } do |f| %>
      <div class="children">
        <%= f.fields_for :children do |c| %>
          <% if c.object.id.nil? %>
            <%= render 'child_field', f: c %>
          <% end %>
        <% end %>
      </div>
      <div class="row">
        <div class="col-sm-offset-1 col-sm-10 form-inline">
          Quantity <span id="original">(<%= (@specimen.quantity ? @specimen.quantity_with_unit : 'nil') %>)<span> is 
          <%= f.text_field :quantity_with_unit, class: "form-control input-sm parent quantity", id: "parent_quantity_with_unit", size: 5, readonly: true %>
          <div class="btn-group" data-toggle="buttons">
            <%= label_tag :manual, class: "btn btn-default btn-sm" do %>
              <%= check_box_tag :manual, true, false, autocomplete: "off" %>
              <span class="glyphicon glyphicon-minus"></span>
            <% end %>
          </div>
          and loss is
          <span id="divided_loss">0.0 g</span>
          after operation <%= f.text_field :comment, placeholder: "cut by saw", class: "form-control input-sm", size: 12 %>.
        </div>
        <div class="col-sm-1">
          <%= f.button class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </div>        
      </div>
    <% end %>
    <%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#specimen-bundle-form').submit();", class: "btn btn-default" %>
  </div>
</div>

<%= javascript_tag do %>
  //ロスの計算
  function quantity_change_check() {
    var $form = $("form#divide_specimen");
    $.ajax({
      url: '<%= loss_divide_specimen_path %>',
      type: 'put',
      data: $form.serialize(),
      success: function(result){
        $("#parent_quantity").val(result.parent_quantity);
        $("#parent_quantity_unit").val(result.parent_quantity_unit);
        $("#parent_quantity_with_unit").val(result.parent_quantity + " " + result.parent_quantity_unit);        
        $("#divided_loss").text(result.loss_quantity + " " + result.loss_quantity_unit);
      }
    });
  };

  $(document).on("change", "input.quantity", function() {
    quantity_change_check();
  });

  $(document).on("click", ".remove-quantity-child", function() {
    quantity_change_check();
  });

  $(document).on("change", "#manual", function() {
    if ($(this).prop('checked')) {
      $("input.parent.quantity").attr("readonly", false);
      $(this).next().removeClass("glyphicon-minus");
      $(this).next().addClass("glyphicon-ok");
    } else {
      $("input.parent.quantity").attr("readonly", true);
      $(this).next().removeClass("glyphicon-ok");
      $(this).next().addClass("glyphicon-minus");
    }
    quantity_change_check();
  });

  $(document).on("succeed.ajaxForm", "#divide_specimen", function() {
    location.href="<%= specimen_path(@specimen) %>";
  });

  $(document).on("click", "input.select-row-all-div", function() {
    $(document).find("input.select-row").prop("checked", $(this).prop("checked"));
  });


<% end %>

app/views/specimens/_file.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>name</th>
      <th></th>
      <th>spots</th>
      <th>global-id</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag bundle_edit_attachment_files_path, id: "attachment-file-bundle-form" do %>
      <% @specimen.attachings.where(attachable_type: "Specimen").order("position ASC").each do |attaching| %>
        <% next unless attaching.attachment_file %>
        <tr>
          <% attachment_file = attaching.attachment_file %>
          <td>
            <%= check_box_tag("ids[]", attachment_file.id, checked: false, id: "ids_#{attachment_file.id}", class: "select-row") if can?(:update, attachment_file) %>
          </td>
          <td><%= attachment_file.decorate.picture(width: 70, height: 70, type: :thumb) %></td>
          <td><%= link_to_if can?(:read, attachment_file), list_title(attachment_file), attachment_file %></td>
          <td>
            <% if attachment_file.pdf? %>
              <%= link_to(image_tag("icon_pdf_1.png", size: "24x24"), download_attachment_file_path(attachment_file.id), id: "file-#{attachment_file.id}-button") %>
            <% end %>
          </td>
          <td><%= attachment_file.spots.try!(:size) %></td>
          <td><%= attachment_file.try!(:global_id) %></td> 
          <td>
            <%= link_to move_to_top_attaching_path(attaching) + tab_param(__FILE__), method: :move_to_top ,title: "move to top" do %>
              <span class="glyphicon glyphicon-arrow-up"></span>
            <% end %>
          </td>
          <td>
            <%= link_to specimen_attachment_file_path(@specimen, attachment_file) + tab_param(__FILE__), method: :delete, title: "unlink attachment file", data: {confirm: t("confirm.unlink")} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_for AttachmentFile.new, url: specimen_attachment_files_path(@specimen), multipart: true do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <%= f.fields_for :record_property_attributes do |r| %>
          <%= r.hidden_field :user_id ,value: @current_user.id %>
        <% end %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th colspan= "2">
          <%= f.file_field :data %>
        </th>
        <th>
          <%= f.button title:"add attachment file", class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
        <th>
        </th>
      <% end %>
      <%= form_tag link_by_global_id_specimen_attachment_files_path(@specimen), method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, nil, id: "attachment-file-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to attachment_files_path(per_page: 5, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#attachment-file-global-id" do %>
	      <span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link attachment file by global id", class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </tfoot>
</table>
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#attachment-file-bundle-form').submit();", class: "btn btn-default" %>
<br/>
To upload and link a file to <%= @alias_specimen %>, use interface at the bottom.

app/views/specimens/chemistries.modal.erb
<%= high_chart("sample", @graph) %>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>            
    </tr>
  </thead>
  <tbody>
    <h3><%=raw @measurement_item.display_in_html %></h3>
    <% @chemistries.each do |chemistry| %>
    <tr>
      <td><%=link_to(chemistry.specimen.name, specimen_path(chemistry.specimen)) if chemistry.specimen %></td>
      <td><%=link_to(chemistry.analysis.name, analysis_path(chemistry.analysis)) %></td>
      <td><%=chemistry.value %><%=" (#{chemistry.uncertainty})" if chemistry.uncertainty %></td>
      <td><%=raw chemistry.unit.html if chemistry.unit %></td>      
    </tr>
    <% end %>
  </tbody>
</table>