config/routes.rb
  get "surfaces/index"
  get "surfaces/show"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: "users"
             }
  resources :tokens, only: :create

  root 'records#index'

  concern :bundleable do
    collection do
      post :bundle_edit
      post :bundle_update
    end
  end

  concern :reportable do
    member do
      get :download_card
      get :download_label
    end
    collection do
      get :download_bundle_card
      get :download_bundle_label
      get :download_bundle_list
    end
  end

  concern :link_by_global_id do
    collection do
      post :link_by_global_id
    end
  end

  concern :inventory do
    member do
      post :inventory
    end
  end

  concern :multiple do
    collection do
      get :multiple_new
      post :multiple_create
    end
  end

  concern :sesar_upload do
    member do
      post :sesar_upload
    end
  end

  resources :records, { id: /((?!\.(html$|json$|xml$|pml$)).)*/ } do
    member do
      get 'record_property' => 'records#property'
      get 'casteml'
      get 'ancestors'
      get 'descendants'
      get 'self_and_descendants'
      get 'pmlame'
      get 'root'
      get 'parent'
      get 'daughters'
      get 'siblings'
      get 'self_and_siblings'
      get 'families'
      put :dispose
      patch :dispose
      put :restore
      patch :restore
      put :lose
      patch :lose
      put :found
      patch :found
      put :publish
      patch :publish
    end
  end

  resources :specimens, concerns: [:bundleable, :reportable, :sesar_upload], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      get :detail_edit
      get :chemistries
      get :place, to: :show_place
      post :place, to: :create_place
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "specimen" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "specimen" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "specimen" }
    resources :daughters, concerns: [:link_by_global_id], only: [:index, :create,:update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "specimen" }
  end

  resources :divide_specimens, only: [:update] do
    member do
      put :loss
    end
  end

  resources :divides, only: [:edit, :update, :destroy] do
    member do
      put :loss
    end
  end

  resources :boxes, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :property
      get :tree_node
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "box" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "box" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "box" }
    resources :specimens, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "box", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "box", association_name: "children" }
  end

  resources :places, concerns: [:bundleable, :reportable] do
    member do
      get :map
      get :property
    end
    collection do
      post :import
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id],only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "place" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "place", association_name: "specimens" }
  end

  resources :analyses, concerns: :bundleable do
    member do
      get :picture
      get :property
      get :casteml
    end
    collection do
      post :import
      get :table
      get :castemls
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "analysis" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "analysis" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "analysis" }
    resources :chemistries, concerns: [:multiple],only: [:index, :create, :update, :destroy], controller: "nested_resources/chemistries"
  end

  resources :bibs, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      put :publish
    end
    collection do
      get :download_to_tex
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "bib" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "bib", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "bib", association_name: "boxes" }
    resources :places, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/places", defaults: { parent_resource: "bib", association_name: "places" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "bib", association_name: "analyses" }
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "bib" }
    resources :tables, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/tables", defaults: { parent_resource: "bib" }
  end

  resources :surfaces, concerns: [:bundleable, :reportable] do
    member do
      get :family
      get :picture
      get :property
      get :map
    end
    resources :images, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_images" do
      member do
        get :family
        post 'move_to_top'
        post 'tiles'
        get :calibrate
      end
    end
    resources :spots, only: [:index, :create, :update, :destroy], controller: "nested_resources/spots"
    resources :layers, only: [:show, :create, :edit, :update, :destroy], controller: "surface_layers" do
      member do
        post 'move_to_top'
      end
    end
  end

  resources :tables, except: [:new] do
    member do
      get :property
      put :publish
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "table", association_name: "specimens" }
  end

  resources :attachment_files, concerns: :bundleable , except: [:new] do
    member do
      get :property
      get :picture
      get :download
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "attachment_file" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end

app/models/box_type.rb
class BoxType < ActiveRecord::Base
  has_many :boxes

  validates :name, presence: true, length: {maximum: 255}
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  respond_to :html, :xml, :json
  before_action :find_resource, except: [:index, :create, :show, :bundle_edit, :bundle_update, :download_card, :download_bundle_card, :download_label, :download_bundle_label]
  before_action :find_resources, only: [:bundle_edit, :bundle_update, :download_bundle_card, :download_bundle_label]
  load_and_authorize_resource

  def index
    @search = Box.includes(:parent).readables(current_user).search(params[:q])
    @search.sorts = "updated_at DESC" if @search.sorts.empty?
    @boxes = @search.result.includes(:box_type).page(params[:page]).per(params[:per_page])
    respond_with @boxes
  end

  def show
    # @contents_search = Path.search(exists_at: Date.today.strftime("%Y%m%d"))
    # @contents_search.sorts = "path ASC"
    # @contents = Path.none
    # @contents = @contents.page(1).per(10)
    #if params[:q]
    separator = "-----"
    @button_action_selection_items = ["", "recent", "snapshot", separator]
    duration_numbers = [1]
    ["in/out from", "integ from", "diff from" ].each do |prefix|
      ["day", "week", "month", "year"].each do |str|
          duration_numbers.each do |num| 
            @button_action_selection_items << "#{prefix} #{num} #{str.pluralize(num)} ago"
          end
      end
    end
    @button_action_selection_items = @button_action_selection_items.map{|item| [item, item]}

    params[:q] = {} unless params[:q]

    if !(params[:dst_date].blank?)
      @dst_date = params[:dst_date]
    else
      @dst_date = Date.today.strftime("%Y-%m-%d")
    end

    if !(params[:src_date].blank?)
      @src_date = params[:src_date]
    else
      ddate = Date.strptime(@dst_date, "%Y-%m-%d")
      if m = /from (\d*) (.*) ago/.match(params[:button_action])
        sdate = convert_date(ddate, m[1], m[2])
      else
        oldest = Path.order(brought_in_at: :asc).first
        if oldest
          sdate = oldest.brought_in_at
        else
          sdate = convert_date(ddate, "10", "years")
        end
      end
      @src_date = sdate.strftime("%Y-%m-%d")
    end

    if Time.zone.parse(@dst_date).today?
      dst_date_time = Time.zone.now
    else
      dst_date_time = Time.zone.parse(@dst_date).end_of_day
    end

    default_sorts = "path ASC"
    if params[:button_action].blank? || params[:button_action] == separator
      @contents_search = Path.search(params[:q])
      @contents_search.sorts = "path ASC"
      @contents = Path.none
      @contents = @contents.page(params[:page]).per(params[:per_page])
    else
      case params[:button_action]
      when /diff/
        @contents_search = Path.diff(@box, @src_date, dst_date_time).search(params[:q])
      when /integ/
        @contents_search = Path.integ(@box, @src_date, dst_date_time).search(params[:q])
      when /snapshot/
        @contents_search = Path.snapshot(@box, dst_date_time).search(params[:q])
      else
        # in/out
        @contents_search = Path.change(@box, @src_date, dst_date_time).search(params[:q])
        default_sorts = ["brought_at DESC", "sign ASC"]
      end
      @contents_search.sorts = default_sorts if @contents_search.sorts.empty?
      @contents = @contents_search.result
      #@contents = @contents.current if @contents_search.conditions.empty?
      @contents = @contents.page(params[:page]).per(params[:per_page])
    end
    @box = Box.includes(children: [:record_property, :box_type], specimens: [:record_property, :analyses, :physical_form]).find(params[:id]).decorate
    respond_with @box
  end

  def edit
    respond_with @box, layout: !request.xhr?
  end

  def create
    @box = Box.new(box_params)
    @box.save
    respond_with @box
  end

  def update
    @box.update_attributes(box_params)
    respond_with @box
  end

  def destroy
    @box.destroy
    respond_with @box
  end

  def family
    respond_with @box, layout: !request.xhr?
  end

  def picture
    respond_with @box, layout: !request.xhr?
  end

  def property
    respond_with @box, layout: !request.xhr?
  end

  def tree_node
    record_property_id = params[:record_property_id].to_i
    klass = params[:klass].constantize
    depth = params[:depth].to_i + 1
    object = RecordProperty.find(record_property_id).datum.decorate
    render json: { tree_node: object.tree_nodes(klass, depth) }
  end

  def bundle_edit
    respond_with @boxes
  end

  def bundle_update
    @boxes.each { |box| box.update_attributes(box_params.only_presence) }
    render :bundle_edit
  end

  def download_card
    report = Box.find(params[:id]).build_card
    send_data(report.generate, filename: "box.pdf", type: "application/pdf")
  end

  def download_bundle_card
    method = (params[:a4] == "true") ? :build_a_four : :build_cards
    report = Box.send(method, @boxes)
    send_data(report.generate, filename: "boxes.pdf", type: "application/pdf")
  end

  def download_label
    box = Box.find(params[:id])
    send_data(box.build_label, filename: "box_#{box.id}.label", type: "text/label")
  end

  def download_bundle_label
    label = Box.build_bundle_label(@boxes)
    send_data(label, filename: "boxes.label", type: "text/label")
  end
  
  private

  def box_params
    params.require(:box).permit(
      :name,
      :parent_global_id,
      :parent_id,
      :position,
      :path,
      :box_type_id,
      :quantity,
      :quantity_unit,
      :tag_list,
      :user_id,
      :description,
      :group_id,
      :published,
      :fixed_in_box,
      record_property_attributes: [
        :id,
        :global_id,
        :user_id,
        :group_id,
        :owner_readable,
        :owner_writable,
        :group_readable,
        :group_writable,
        :guest_readable,
        :guest_writable,
        :published,
        :lost
      ]
    )
  end

  def find_resource
    @box = Box.find(params[:id]).decorate
  end

  def find_resources
    @boxes = Box.where(id: params[:ids])
  end

  def convert_date(date, value, unit)
    case unit
    when "day", "days"
      date.days_ago(value.to_i)
    when "week", "weeks"
      date.weeks_ago(value.to_i)
    when "month", "months"
      date.months_ago(value.to_i)
    when "year", "years"
      date.years_ago(value.to_i)
    else
      date.days_ago(1)
    end
  end

end

app/views/boxes/_bib.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th colspan= "2">name</th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag bundle_edit_bibs_path, id: "bib-bundle-form" do %>
      <% @box.bibs.each do |bib| %>
        <tr>
          <td>
              <%= check_box_tag("ids[]", bib.id, false, {id: "ids_#{bib.id}", class: "select-row"}) if can?(:update, bib) %>
            </td>
          <td colspan="2"><%= link_to_if can?(:read, bib), list_title(bib), bib %></td>
          <td><%= bib.try!(:global_id) %></td>
          <td>
            <%= link_to box_bib_path(@box,bib) + tab_param(__FILE__), method: :delete ,title: "unlink bib",data: {confirm: t("confirm.unlink")} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
     <%= form_for Bib.new, url: box_bibs_path(@box) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th><%#= f.text_field :name, class: "form-control input-sm" %></th>
        <th>
          <%#= f.button title:"add bib",class: "btn btn-default" do %>
            <%#<span class="glyphicon glyphicon-save"></span> %>
          <%# end %>
        </th>
      <% end %>
    <%= form_tag link_by_global_id_box_bibs_path(@box),method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, "", id: "bib-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to bibs_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#bib-global-id" do %>
	      <span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link bib by global id",class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
    <tr>
  </tfoot>
</table>
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#bib-bundle-form').submit();", class: "btn btn-default" %>

app/views/boxes/_specimen.html.erb
<div class="display-type">
  <div id="display-type-html">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="panel panel-default">
	  <div class="panel-heading">
	  </div>
	  <table class="table table-condensed">
	    <tbody>
              <%= form_tag bundle_edit_specimens_path, id: "specimen-bundle-form" do %>
		<% @box.specimens.each do |specimen| %>
		  <% specimen = specimen.decorate %>
		  <tr>
		    <td class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
		      <%= qrcode specimen.global_id, size: "80x80" %>
		      <%= check_box_tag("ids[]", specimen.id, true, {id: "ids_#{specimen.id}", class: "select-row"}) if can?(:update, specimen) %>
		      <%= link_to box_specimen_path(@box, specimen) + tab_param(__FILE__), method: :delete, title: "unlink specimen", data: {confirm: t("confirm.unlink")} do %>
			<span class="glyphicon glyphicon-remove"></span>
		      <% end %>
		    </td>
		    <td class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
		      <%= link_to specimen.attachment_files.first.decorate.picture(width: 160, height: 160, type: :thumb), specimen, class: specimen_ghost(specimen) if specimen.attachment_files.present? %>
		    </td>

		    <td class="col-xs-7 col-sm-7 col-md-7 col-lg-7">

		      <%= specimen.name_with_id(true) %>
		      <ul>
			<% unless specimen.igsn.blank? %>
			  <li>
			    IGSN: <%= link_to specimen.igsn, Settings.sesar_url(igsn: specimen.igsn) %>
			    <%= link_to Settings.sesar_url(igsn: specimen.igsn, edit: true), title: "edit on SESAR" do %>
			      <span class="glyphicon glyphicon-pencil"></span>
			    <% end %>

			  </li>
			<% end %>
			<% if specimen.place %>
			  <% place = specimen.place.decorate %>
			  <li>
			    place: <%= raw(place.try!(:latitude_to_html)) + ", " + raw(place.try!(:longitude_to_html)) %> <%= link_to "more", place_path(place) %>
			  </li>
			<% end %>
			<%= li_if_exist("classification: ", specimen.classification.try!(:full_name)) %>
			<%= li_if_exist("physical-form: ", specimen.physical_form.try!(:name)) %>
			<%= li_if_exist("quantity (#{specimen.quantity_unit}): ", specimen.quantity) %>
			<%= content_tag(:li, "status: #{specimen.status_icon} (#{specimen.status_name})", {}, false) if specimen.status_name.present? %>
			<%= li_if_exist("age (#{specimen.age_unit}): ", specimen.age_in_text) %>
			<%= li_if_exist("tag list: ", specimen.tag_list) %>
			<%= li_if_exist("description: ", specimen.description) %>
			<% specimen.specimen_custom_attributes.each do |specimen_custom_attribute| %>
			  <%= li_if_exist("#{specimen_custom_attribute.custom_attribute.name}: ", specimen_custom_attribute.value ) %>
			<% end %>
			<li>modified at <%= difference_from_now(specimen.updated_at) %></li>
		      </ul>
		    </td>
		  </tr>
		<% end %>
              <% end %>
	    </tbody>
	  </table>
	</div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#specimen-bundle-form').submit();", class: "btn btn-default" %>
	<div class="panel panel-default">
	  <div class="panel-heading">
	  </div>
	  <table class="table table-condensed">
	    <tr>
	      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<%= form_tag link_by_global_id_box_specimens_path(@box),method: :post do %>
		  <%= hidden_tabname_tag(__FILE__) %>
		  <div class="input-group">
		    <%= text_field_tag :global_id, nil, id: "specimen-global-id", :placeholder => "input ID", class: "form-control input-sm" %>
		    <span class="input-group-addon">
		      <%= link_to specimens_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#specimen-global-id" do %>
			<span class="glyphicon glyphicon-search"></span>
		      <% end %>
		    </span>

		  </div>
		  <%= button_tag title: "link specimen by global id", class: "btn btn-default" do %>
                    <span class="glyphicon glyphicon-save"></span>
		  <% end %>
		<% end %>
	      </td>
	      <td class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

		<%= form_for Specimen.new, url: box_specimens_path(@box) do |f|%>
		  <%= hidden_tabname_tag(__FILE__) %>
		  <%= f.text_field :name, :placeholder => "input name", class: "form-control input-sm" %>
		  <%= f.select :physical_form_id, PhysicalForm.pluck(:name, :id), { prompt: "select physical form" }, class: "form-control input-sm" %>
		  <%= f.text_field :quantity, :placeholder => "input quantity", class: "form-control input-sm" %>
		  <%= f.text_field :quantity_unit, :placeholder => "input quantity unit", class: "form-control input-sm" %>
		  <%= f.button title:"add specimen file", class: "btn btn-default" do %>
                    <span class="glyphicon glyphicon-save"></span>
		  <% end %>
		<% end %>
	      </td>
	    </tr>
	  </table>
	</div>
      </div>
    </div>
  </div>
  <div class="hidden" id="display-type-tex">
    <pre><code><%= @box.to_tex(@alias_specimen) %></code></pre>
  </div>
</div>
<div class="btn-group">
  <a href="#display-type-html" class="btn radio-button-group">html</a>
  <a href="#display-type-tex" class="btn radio-button-group">tex</a>
</div>

app/views/boxes/family.html.erb
<div>
  <% if @box.attachment_files.present? %>
    <%= link_to(@box.primary_picture, attachment_file_path(@box.attachment_files.first)) %>
  <% end %>
</div>
<div id="family-tree">
  <%= @box.family_tree %>
</div>

app/views/boxes/show.html.erb
<%= javascript_tag do %>
  $(document).on("click", "span.badge", function() {
    var $data = $(this).data();
    $data.depth = $(this).parent().parent().data('depth');
    var content = '#tree-' + $data.klass + '-' + $data.record_property_id
    if ($(content).html() == "") {
      $.ajax({
        url: '<%= tree_node_box_path %>',
        type: 'get',
        data: $data,
        success: function(result){
          $(content).replaceWith(result.tree_node);
          $(content).removeClass('in');
          $("a[href = " + content + "]").click();
        }
      });
    }
  });
<% end %>
<div class="row">
  <div id="show-caption" class="col-lg-12">
    <%= @box.box_path_with_id %> <%= published_label(@box) %>
  </div>
</div>
<div class="row">
  <div id="show-tools" class="col-lg-4">
    <div class="row btn-toolbar tool-selector" role="toolbar">
      <div class="btn-group btn-group-sm">
        <%= link_to family_box_path(@box), class: "btn btn-default activate",  id: "tree-conifer-button", remote: true do %>
          <span class="glyphicon glyphicon-tree-conifer"></span>
        <% end %>
        <% if @box.has_image? %>
          <%= link_to picture_box_path(@box), class: "btn btn-default", id: "picture-button", remote: true do %>
            <span class="glyphicon glyphicon-picture"></span>
          <% end %>
        <% end %>
      </div>
      <% if can? :update, @box %>
      <div class="btn-group btn-group-sm">
        <%= link_to edit_box_path(@box), class: "btn btn-default", id: "pencil-button", remote: true do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to property_box_path(@box), class: "btn btn-default", id: "cog-button", remote: true do %>
          <span class="glyphicon glyphicon-cog"></span>
        <% end %>
      </div>
      <% end %>
      <div class="btn-group btn-group-sm">
        <%= link_to download_label_box_path(@box), class: "btn btn-default", id: "tag-button" do %>
          <span class="glyphicon glyphicon-tag"></span>
        <% end %>
        <%= link_to download_card_box_path(@box), class: "btn btn-default", id: "file-button" do %>
          <span class="glyphicon glyphicon-file"></span>
        <% end %>
      </div>
    </div>
    <img>
    <div class="row tool-content">
    </div>
  </div>

  <div id="show-body" class="col-lg-8">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
      <li class="<%= active_if_current('at-a-glance') %>">
        <a href="#at-a-glance" data-toggle="tab">at-a-glance</a>
      </li>
      <li class="<%= active_if_current('specimen') %>">
        <a href="#specimen" data-toggle="tab"><%= @alias_specimen + data_count(@box.specimens) %></a>
      </li>
      <li class="<%= active_if_current('daughter') %>">
        <a href="#daughter" data-toggle="tab"><%= "box#{data_count(@box.children)}" %></a>
      </li>
      <li class="<%= active_if_current('history') %>">
        <a href="#history" data-toggle="tab"><%= "history#{data_count(@box.paths)}" %></a>
      </li>
      <li class="<%= active_if_current('analysis') %>">
        <a href="#analysis" data-toggle="tab"><%= "analysis#{data_count(@box.analyses)}" %></a>
      </li>
      <li class="<%= active_if_current('bib') %>">
        <a href="#bib" data-toggle="tab"><%= "bib#{data_count(@box.bibs)}" %></a>
      </li>
      <li class="<%= active_if_current('file') %>">
        <a href="#file" data-toggle="tab"><%= "file#{data_count(@box.attachment_files)}" %></a>
      </li>
    </ul>

    <!-- Tab panes -->
    <% tab_info = [
        ["at-a-glance",nil],
        ["specimen",@box.specimens],
        ["daughter",@box.children,"box"],
        ["history", @box.paths],
        ["analysis",@box.analyses],
        ["bib",@box.bibs],
        ["file",@box.attachment_files]
    ] %>
    <div class="tab-content">
      <% tab_info.each do |key,array| %>
        <div class="tab-pane<%= active_if_current(key) %>" id="<%= key %>"><%= render partial: key.underscore %></div>
      <% end %>
    </div>
  </div>
</div>