config/routes.rb
Medusa::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get "surfaces/index"
  get "surfaces/show"
  devise_for :users, controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               registrations: "users"
             }
  resources :tokens, only: :create

  root 'records#index'

  concern :bundleable do
    collection do
      post :bundle_edit
      post :bundle_update
    end
  end

  concern :reportable do
    member do
      get :download_card
      get :download_label
    end
    collection do
      get :download_bundle_card
      get :download_bundle_label
      get :download_bundle_list
    end
  end

  concern :link_by_global_id do
    collection do
      post :link_by_global_id
    end
  end

  concern :inventory do
    member do
      post :inventory
    end
  end

  concern :multiple do
    collection do
      get :multiple_new
      post :multiple_create
    end
  end

  concern :sesar_upload do
    member do
      post :sesar_upload
    end
  end

  resources :records, { id: /((?!\.(html$|json$|xml$|pml$)).)*/ } do
    member do
      get 'record_property' => 'records#property'
      get 'casteml'
      get 'ancestors'
      get 'descendants'
      get 'self_and_descendants'
      get 'pmlame'
      get 'root'
      get 'parent'
      get 'daughters'
      get 'siblings'
      get 'self_and_siblings'
      get 'families'
      put :dispose
      patch :dispose
      put :restore
      patch :restore
      put :lose
      patch :lose
      put :found
      patch :found
      put :publish
      patch :publish
    end
  end

  resources :specimens, concerns: [:bundleable, :reportable, :sesar_upload], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      get :detail_edit
      get :chemistries
      get :place, to: :show_place
      post :place, to: :create_place
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "specimen" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "specimen" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "specimen" }
    resources :daughters, concerns: [:link_by_global_id], only: [:index, :create,:update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "specimen", association_name: "children" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "specimen" }
  end

  resources :divide_specimens, only: [:update] do
    member do
      put :loss
    end
  end

  resources :divides, only: [:edit, :update, :destroy] do
    member do
      put :loss
    end
  end

  resources :boxes, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :property
      get :tree_node
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "box" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "box" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "box" }
    resources :specimens, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "box", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id, :inventory], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "box", association_name: "children" }
  end

  resources :places, concerns: [:bundleable, :reportable] do
    member do
      get :map
      get :property
    end
    collection do
      post :import
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id],only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "place" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "place", association_name: "specimens" }
  end

  resources :analyses, concerns: :bundleable do
    member do
      get :picture
      get :property
      get :casteml
    end
    collection do
      post :import
      get :table
      get :castemls
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "analysis" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "analysis" }
    resources :bibs, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/bibs", defaults: { parent_resource: "analysis" }
    resources :chemistries, concerns: [:multiple],only: [:index, :create, :update, :destroy], controller: "nested_resources/chemistries"
  end

  resources :bibs, concerns: [:bundleable, :reportable], except: [:new] do
    member do
      get :family
      get :picture
      get :map
      get :property
      put :publish
    end
    collection do
      get :download_to_tex
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "bib" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore
        put :lose
        patch :lose
        put :found
        patch :found
      end
    end
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "bib", association_name: "specimens" }
    resources :boxes, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/boxes", defaults: { parent_resource: "bib", association_name: "boxes" }
    resources :places, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/places", defaults: { parent_resource: "bib", association_name: "places" }
    resources :analyses, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/analyses", defaults: { parent_resource: "bib", association_name: "analyses" }
    resources :attachment_files, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/attachment_files", defaults: { parent_resource: "bib" }
    resources :tables, concerns: [:link_by_global_id], only: [:index,:create, :update, :destroy], controller: "nested_resources/tables", defaults: { parent_resource: "bib" }
  end

  resources :surfaces, concerns: [:bundleable, :reportable] do
    member do
      get :family
      get :picture
      get :property
      get :map
    end
    resources :images, concerns: [:link_by_global_id], only: [:index, :show, :create, :update, :destroy], controller: "surface_images" do
      member do
        get :family
        post 'move_to_top'
        post 'tiles'
        get :calibrate
      end
    end
    resources :spots, only: [:index, :create, :update, :destroy], controller: "nested_resources/spots"
    resources :layers, only: [:show, :create, :edit, :update, :destroy], controller: "surface_layers" do
      member do
        post 'move_to_top'
      end
    end
  end

  resources :tables, except: [:new] do
    member do
      get :property
      put :publish
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "place" }
    resources :specimens, concerns: [:link_by_global_id], only: [:index, :create, :update, :destroy], controller: "nested_resources/specimens", defaults: { parent_resource: "table", association_name: "specimens" }
  end

  resources :attachment_files, concerns: :bundleable , except: [:new] do
    member do
      get :property
      get :picture
      get :download
    end
    resource :record_property, only: [:show, :update], defaults: { parent_resource: "attachment_file" } do
      member do
        put :dispose
        patch :dispose
        put :restore
        patch :restore

app/models/bib.rb
class Bib < ActiveRecord::Base 
  include HasRecordProperty
  include HasViewSpot
  include OutputPdf
  include HasAttachmentFile

  LABEL_HEADER = ["Id", "Name", "Authors"]

  has_many :bib_authors, -> { order(:priority) }, before_add: :set_initial_position
  has_many :authors, through: :bib_authors, order: 'bib_authors.priority'

  has_many :referrings, dependent: :destroy
  has_many :specimens, through: :referrings, source: :referable, source_type: "Specimen"
  has_many :places, through: :referrings, source: :referable, source_type: "Place"
  has_many :boxes, -> { order(:name) }, through: :referrings, source: :referable, source_type: "Box"
  has_many :analyses, through: :referrings, source: :referable, source_type: "Analysis"
  has_many :tables, before_add: :take_over_specimens

  accepts_nested_attributes_for :bib_authors

  validates :name, presence: true, length: { maximum: 255 }
  validate :author_valid?, if: Proc.new{|bib| bib.authors.blank?}
  

  def related_spots
    sps = []
    # specimens.each do |specimen|
    #   sps.concat(specimen.related_spots)
    # end
#    sps = ancestors.map{|box| box.spot_links }.flatten || []
#    sps.concat(box.related_spots) if box
    sps
  end

  def as_json(options = {})
    super({:methods => [:author_ids, :global_id, :pmlame_ids]}.merge(options))
  end

  def specimen_places
    Place.eager_load(:specimens).where(specimens: {id: self.specimen_ids})
  end

  def table_specimens
    Specimen.eager_load(:table_specimens).where(tables: {id: self.table_ids})
  end

  def all_specimens
    self.specimens + self.table_specimens
  end

  def all_places
    rplaces = self.places + self.specimen_places
    rplaces
  end
  
  def referrings_analyses
    ranalyses = self.analyses
    specimens.each do |specimen| 
      (ranalyses = ranalyses + specimen.analyses) unless specimen.analyses.empty?
    end
    boxes.each do |box| 
      (ranalyses = ranalyses + box.analyses) unless box.analyses.empty?
    end
    places.each do |place| 
      (ranalyses = ranalyses + place.analyses) unless place.analyses.empty?
    end
    tables.each do |table|
      (ranalyses = ranalyses + table.analyses) unless table.analyses.empty?
    end
    #p ranalyses.to_sql
    ranalyses.uniq
  end

  def doi_link_url
    return unless doi
    "https://doi.org/#{doi}"
  end
  
  def primary_pdf_attachment_file
    pdf_files.first if pdf_files.present?
  end

  def build_label
    CSV.generate do |csv|
      csv << LABEL_HEADER
      csv << ["#{global_id}", "#{name}", "#{author_lists}"]
    end
  end

  def self.build_bundle_label(bibs)
    CSV.generate do |csv|
      csv << LABEL_HEADER
      bibs.each do |bib|
        csv << ["#{bib.global_id}", "#{bib.name}", "#{bib.author_lists}"]
      end
    end
  end
  
  def self.build_bundle_tex(bibs)
    bibs.map{|bib| bib.to_tex}.join(" ")
  end
  
  def to_tex
    if entry_type == "article"
#      tex = "\n@article{#{abbreviation.presence || global_id},\n#{article_tex},\n}"
      tex = "\n@article{#{global_id},\n#{article_tex},\n}"
    else
#      tex = "\n@misc{#{abbreviation.presence || global_id},\n#{misc_tex},\n}"
      tex = "\n@misc{#{global_id},\n#{misc_tex},\n}"      
    end
    return tex
  end
  
  def article_tex
    bib_array = []
    bib_array << "\tauthor = \"#{author_lists}\""
    bib_array << "\ttitle = \"#{name}\""
    if journal == "DREAM Digital Document"
      bib_array << "\tjournal = {\\href{#{dream_url}}{#{journal}}}"
    else
      bib_array << "\tjournal = \"#{journal}\""
    end
    bib_array << "\tyear = \"#{year}\""
    bib_array << "\tnumber = \"#{number}\"" if number.present?
    bib_array << "\tmonth = \"#{month}\"" if month.present?
    bib_array << "\tvolume = \"#{volume}\"" if volume.present?
    bib_array << "\tpages = \"#{pages}\"" if pages.present?
    bib_array << "\tnote = \"#{note}\"" if note.present?
    bib_array << "\tdoi = \"#{doi}\"" if doi.present?
    bib_array << "\tkey = \"#{key}\"" if key.present?
    bib_array.join(",\n")
  end
  
  def misc_tex
    bib_array = []
    bib_array << "\tauthor = \"#{author_lists}\""
    bib_array << "\ttitle = \"#{name}\""
    bib_array << "\tnumber = \"#{number}\"" if number.present?
    bib_array << "\tmonth = \"#{month}\"" if month.present?
    bib_array << "\tjournal = \"#{journal}\"" if journal.present?
    bib_array << "\tvolume = \"#{volume}\"" if volume.present?
    bib_array << "\tpages = \"#{pages}\"" if pages.present?
    bib_array << "\tyear = \"#{year}\"" if year.present?
    bib_array << "\tnote = \"#{note}\"" if note.present?
    bib_array << "\tdoi = \"#{doi}\"" if doi.present?
    bib_array << "\tkey = \"#{key}\"" if key.present?
    bib_array.join(",\n")
  end

  def author_lists
    authors.pluck(:name).join(" and ")
  end

  def to_html
    html = authors.first.name
    #if authors.size > 2
    #  html = authors[0].name + " et al."
    #else
    #  html = authors.pluck(:name).join(" and ")
    #end
    html += " (#{year})" if year.present?
    html += " #{name}" if name.present?
    html += ", <i>#{journal}</i>" if journal.present?
    html += ", <b>#{volume}</b>" if volume.present?
    html += ", #{pages}" if pages.present?
    return "#{html}."
  end

  def publish!
    objs = [self]
    objs.concat(self.boxes)
    objs.concat(self.places)
    objs.each do |obj|
      obj.published = true
      obj.save
    end
    
    objs_r = []
    objs_r.concat(self.specimens)
    objs_r.concat(self.analyses)
    objs_r.concat(self.tables)
    objs_r.each do |obj|
      obj.publish!
    end
  end

  def pml_elements
    self.referrings_analyses
  end

  private

  def pdf_files
    if attachment_files.present?
      attachment_files.order("updated_at desc").select {|file| file.pdf? }
    end
  end
  
  def author_valid?
    errors[:author] = "can't be blank"
  end

  def set_initial_position(bib_author)
    priority = (bib_authors.maximum(:priority) || 0) + 1
    bib_author.update_attribute(:priority, priority)
  end

  def take_over_specimens(table)
    return if table.ignore_take_over_specimen?
    table.specimens = specimens
  end


end

app/views/places/_at_a_glance.html.erb
<ul>
  <li>country: <%= @place.country_name %></li>
  <li>name: <%= @place.name %></li>
  <li>latitude: <%= raw @place.latitude_to_html %></li>
  <li>longitude: <%= raw @place.longitude_to_html %></li>
  <li>description: <%= @place.try!(:description) %></li>
  <li><%= @alias_specimen %>: <% @place.specimens.each do |specimen| %>
    <%= link_to_if can?(:read, specimen), specimen.decorate.status_icon + specimen.name, specimen_path(specimen), class: specimen_ghost(specimen) %>
  <% end %></li>
  <li>modified at <%= difference_from_now(@place.updated_at) -%></li>
  <% if @place.attachment_pdf_files.present? %>
    <li>
      <% @place.attachment_pdf_files.each do |attachment_pdf_file| %>
        <%= attachment_pdf_file.name %>
        <%= link_to(image_tag("icon_pdf_1.png", size: "24x24"), download_attachment_file_path(attachment_pdf_file.id), id: "file-#{attachment_pdf_file.id}-button") %>
      <% end %>
    </li>
  <% end %>
</ul>
  <% @place.attachment_image_files.each_slice(4) do |files| %>
  <div class="row spot-thumbnails">
    <% files.each do |file| %>
    <div class="col-lg-3">
      <%= link_to attachment_file_path(file), class: "thumbnail" do %>
        <%= image_tag file.path %>
        <%= file.spots.size %> spots
      <% end %>
    </div>
    <% end %>
  </div>
  <% end %>

app/views/places/_file.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>name</th>
      <th></th>
      <th>spots</th>
      <th>global-id</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag bundle_edit_attachment_files_path, id: "attachment-file-bundle-form" do %>
      <% @place.attachings.where(attachable_type: "Place").order("position ASC").each do |attaching| %>
        <tr>
          <% attachment_file = attaching.attachment_file %>
          <td>
            <%= check_box_tag("ids[]", attachment_file.id, false, {id: "ids_#{attachment_file.id}", class: "select-row"}) if can?(:update, attachment_file) %>
          </td>
          <td><%= attachment_file.decorate.picture(width: 70, height: 70, type: :thumb) %></td>
          <td><%= link_to_if can?(:read, attachment_file), list_title(attachment_file),attachment_file %></td>
          <td>
            <% if attachment_file.pdf? %>
              <%= link_to(image_tag("icon_pdf_1.png", size: "24x24"), download_attachment_file_path(attachment_file.id), id: "file-#{attachment_file.id}-button") %>
            <% end %>
          </td>
          <td><%= attachment_file.spots.try!(:size) %></td>
          <td><%= attachment_file.try!(:global_id) %></td> 
          <td>
            <%= link_to move_to_top_attaching_path(attaching) + tab_param(__FILE__), method: :move_to_top ,title: "move to top" do %>
              <span class="glyphicon glyphicon-arrow-up"></span>
            <% end %>
          </td>
          <td>
            <%= link_to  place_attachment_file_path(@place,attachment_file) + tab_param(__FILE__), method: :delete ,title: "unlink attachment file",data: {confirm: t("confirm.unlink")} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_for AttachmentFile.new, url: place_attachment_files_path(@place),multipart: true do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <%= f.fields_for :record_property_attributes do |r| %>
          <%= r.hidden_field :user_id ,value: @current_user.id %>
        <% end %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th colspan= "2"><%= f.file_field :data %></th>
        <th>
          <%= f.button title:"add attachment file",class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
      <th></th>
      <%= form_tag link_by_global_id_place_attachment_files_path(@place),method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id,nil, id: "attachment-file-global-id", class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to attachment_files_path(per_page: 5, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#attachment-file-global-id" do %>
	      <span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link attachment file by global id",class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </tfoot>
</table>
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#attachment-file-bundle-form').submit();", class: "btn btn-default" %>

app/views/places/_neighbor.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th></th>
      <th>distance (km)</th >
      <th>sample</th>
    </tr>
  </thead>
  <body>
    <% @place.readable_neighbors(@current_user).each do |neighbor| %>
      <tr>
        <td></td>
        <td><%= link_to_if can?(:read, neighbor), list_title(neighbor),place_path(neighbor) %></td>
        <td><%= raw neighbor.to_html %></td>
        <td><%= "%0.3f" % neighbor.distance.to_f %></td>
        <td>
          <% neighbor.specimens.each do |specimen| %>
            <%= link_to specimen.name,specimen_path(specimen), class: specimen_ghost(specimen) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/places/_place.modal.erb
<tr>
  <td>
    <%= button_tag class: "btn btn-default btn-xs determine", "data-id" => place.global_id do %>
    <span class="glyphicon glyphicon-link"></span>
    <% end %>
  </td>
  <td><%= link_to place.name, place_path(place, format: :modal), "data-toggle" => "modal", "data-target" => "#show-modal" %></td>
  <td><%= place.latitude_to_text %></td>
  <td><%= place.longitude_to_text %></td>
  <td><%= place.elevation_to_text %></td>
  <td><%= place.specimens_count %></td>
  <td><%= place.group.try!(:name) %></td>
  <td><%= difference_from_now(place.updated_at) %></td>
</tr>

app/views/places/_specimen.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>name</th>
      <th>physical-form</th>
      <th>quantity</th>
      <th>unit</th>
      <th></th>
      <th>global-id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag bundle_edit_specimens_path, id: "specimen-bundle-form" do %>
      <% @place.specimens.each do |specimen| %>
        <tr>
          <td>
            <%= check_box_tag("ids[]", specimen.id, false, {id: "ids_#{specimen.id}", class: "select-row"}) if can?(:update, specimen) %>
          </td>
          <td><%= specimen.decorate.status_icon %></td>
          <td><%= link_to_if can?(:read, specimen), list_title(specimen),specimen, class: specimen_ghost(specimen) %></td>
          <td><%= specimen.physical_form.try!(:name) %></td>
          <td><%= specimen.try!(:quantity) %></td>
          <td><%= specimen.try!(:quantity_unit) %></td>
          <td></td>
          <td><%= specimen.try!(:global_id) %></td> 
          <td>
            <%= link_to place_specimen_path(@place,specimen) + tab_param(__FILE__), method: :delete ,title: "unlink specimen",data: {confirm: t("confirm.unlink")} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <%= form_for Specimen.new, url: place_specimens_path(@place) do |f|%>
        <%= hidden_tabname_tag(__FILE__) %>
        <th><%= check_box_tag nil, nil, false, class: "select-row-all" %></th>
        <th></th>
        <th><%= f.text_field :name, class: "form-control input-sm" %></th>
        <th><%= f.select :physical_form_id, PhysicalForm.pluck(:name, :id), { include_blank: true }, class: "form-control input-sm" %></th>
        <th><%= f.text_field :quantity, class: "form-control input-sm" %></th>
        <th><%= f.text_field :quantity_unit, class: "form-control input-sm" %></th>
        <th>
          <%= f.button title:"add specimen file",class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
      <%= form_tag link_by_global_id_place_specimens_path(@place),method: :post do %>
        <%= hidden_tabname_tag(__FILE__) %>
        <th>
	  <div class="input-group">
	    <%= text_field_tag :global_id, nil, id: "specimen-global-id" ,class: "form-control input-sm" %>
	    <span class="input-group-addon">
	      <%= link_to specimens_path(per_page: 10, format: :modal), "data-toggle" => "modal", "data-target" => "#search-modal", "data-input" => "#specimen-global-id" do %>
	      <span class="glyphicon glyphicon-search"></span>
	      <% end %>
	    </span>
	  </div>
	</th>
        <th>
          <%= button_tag title: "link specimen by global id",class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-save"></span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </tfoot>
</table>
<%= link_to_function content_tag(:span, nil, class: "glyphicon glyphicon-pencil"), "$('#specimen-bundle-form').submit();", class: "btn btn-default" %>

app/views/places/bundle_edit.html.erb
<% if @places.present? %>
  <% place_ids = @places.pluck(:id) %>
  <div class="text-right">
    <%= link_to download_bundle_label_places_path(ids: place_ids) do %>
      <i class="glyphicon glyphicon-tag"></i>
    <% end %>
    ,<%= link_to(image_tag("icon_pdf_1.png", size: "24x24"), download_bundle_card_places_path(ids: place_ids)) %>,
    and <%= link_to("A4", download_bundle_card_places_path(ids: place_ids, a4: true)) %>
  </div>
<% end %>

<%= form_for Place.new, url: bundle_update_places_path do |f| %>
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>latitude</th>
      <th>longitude</th>
      <th>elevation</th>
      <th><%= @alias_specimen %></th>
      <%= th_if_expand "owner" %>
      <th>group</th>
      <%= th_if_expand "published" %>
      <th>updated-at</th>
      <%= th_if_expand "created-at" %>
      <th><%= toggle_column_link method: "post" %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: :place, collection: PlaceDecorator.decorate_collection(@places), locals: { checked: true } %>
  </tbody>
  <tfoot>
    <tr>
      <th><%= check_box_tag nil, nil, true, class: "select-row-all" %></th>
      <th></th>
      <th><%= f.text_field :latitude,class: "form-control input-sm", class: "form-control input-sm" %></th>
      <th><%= f.text_field :longitude,class: "form-control input-sm", class: "form-control input-sm" %></th>
      <th><%= f.text_field :elevation,class: "form-control input-sm", class: "form-control input-sm" %></th>
      <th></th>
      <%= th_if_expand do %>
        <%= f.select :user_id ,User.pluck(:username, :id), { include_blank: true }, class: "form-control input-sm" %>
      <% end %>

      <th><%= f.select :group_id ,Group.pluck(:name, :id), { include_blank: true }, class: "form-control input-sm" %></th>
      <%= th_if_expand do %>
        <%= f.select :published ,[true, false], { include_blank: true }, class: "form-control input-sm" %>
      <% end %>
      <th>
	<%= f.button class: "btn btn-default" do %>
	<span class="glyphicon glyphicon-save"></span>
	<% end %>
      </th>
      <th></th>
    </tr>
  </tfoot>
</table>
<% end %>

app/views/places/import_invalid.html.erb
<div class="alert alert-danger">
  CSV is invalid.
</div>